export const LOAD_RECENT_BOOKS = "LOAD_RECENT_BOOKS";
export const SERVER_REQUEST_ERROR = "SERVER_REQUEST_ERROR";
export const LOAD_CURRENT_BOOK = "LOAD_CURRENT_BOOK";
export const LOAD_SEARCH_RESULT = "LOAD_SEARCH_RESULT"
export const SET_CURRENT_BOOK = "SET_CURRENT_BOOK"

